/**
 * 시스템 전체에서 사용되는 에러 코드 정의
 * 
 * @description
 * GlobalExceptionFilter에서 일관된 에러 처리를 위해 사용되는 표준화된 에러 코드입니다.
 * 각 에러 코드는 특정 비즈니스 상황과 HTTP 상태 코드에 매핑됩니다.
 */
export enum ErrorCode {
  // === 일반적인 HTTP 에러들 ===
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED', 
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  // === 포스트 관련 에러들 ===
  POST_NOT_FOUND = 'POST_NOT_FOUND',
  POST_SLUG_DUPLICATE = 'POST_SLUG_DUPLICATE',
  POST_ALREADY_PUBLISHED = 'POST_ALREADY_PUBLISHED',
  POST_NOT_PUBLISHED = 'POST_NOT_PUBLISHED',

  // === 카테고리 관련 에러들 ===
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  CATEGORY_SLUG_DUPLICATE = 'CATEGORY_SLUG_DUPLICATE',
  CATEGORY_HAS_POSTS = 'CATEGORY_HAS_POSTS',

  // === 태그 관련 에러들 ===
  TAG_NOT_FOUND = 'TAG_NOT_FOUND',
  TAG_SLUG_DUPLICATE = 'TAG_SLUG_DUPLICATE',
  TAG_HAS_POSTS = 'TAG_HAS_POSTS',

  // === 인증/인가 관련 에러들 ===
  INVALID_JWT_TOKEN = 'INVALID_JWT_TOKEN',
  JWT_TOKEN_EXPIRED = 'JWT_TOKEN_EXPIRED',
  JWT_TOKEN_MALFORMED = 'JWT_TOKEN_MALFORMED',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  ADMIN_ONLY_RESOURCE = 'ADMIN_ONLY_RESOURCE',

  // === 데이터베이스 관련 에러들 ===
  DATABASE_CONNECTION_FAILED = 'DATABASE_CONNECTION_FAILED',
  DATABASE_QUERY_FAILED = 'DATABASE_QUERY_FAILED',
  UNIQUE_CONSTRAINT_VIOLATION = 'UNIQUE_CONSTRAINT_VIOLATION',
  FOREIGN_KEY_CONSTRAINT_VIOLATION = 'FOREIGN_KEY_CONSTRAINT_VIOLATION',
  CHECK_CONSTRAINT_VIOLATION = 'CHECK_CONSTRAINT_VIOLATION',
  NOT_NULL_CONSTRAINT_VIOLATION = 'NOT_NULL_CONSTRAINT_VIOLATION',

  // === 유효성 검사 에러들 ===
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  INVALID_REQUEST_FORMAT = 'INVALID_REQUEST_FORMAT',
  INVALID_QUERY_PARAMETERS = 'INVALID_QUERY_PARAMETERS',
  INVALID_REQUEST_BODY = 'INVALID_REQUEST_BODY',
  INVALID_PATH_PARAMETERS = 'INVALID_PATH_PARAMETERS',

  // === 파일 업로드 관련 에러들 ===
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE = 'INVALID_FILE_TYPE',
  FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED',

  // === CSRF 보안 관련 에러들 ===
  CSRF_TOKEN_MISSING = 'CSRF_TOKEN_MISSING',
  CSRF_TOKEN_INVALID = 'CSRF_TOKEN_INVALID',

  // === 외부 서비스 관련 에러들 ===
  EXTERNAL_SERVICE_UNAVAILABLE = 'EXTERNAL_SERVICE_UNAVAILABLE',
  EXTERNAL_SERVICE_TIMEOUT = 'EXTERNAL_SERVICE_TIMEOUT',
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
}